name: First Workflow Template
on: workflow_dispatch
jobs:
    first-workflow:
        runs-on: ubuntu-latest
        steps:
            - name: Print Info
              run: echo "Alpha Bravo Charlie"
